import { useCallback, useEffect, useState } from "react";
import { ChevronLeft, FolderOpen, RefreshCw, X } from "lucide-react";
import { API_BASE } from "../../lib/config";

interface RcloneEntry { Path: string; Name: string; IsDir: boolean; }
interface CloudPathPickerProps { currentPath: string; onSelect: (path: string) => void; onClose: () => void; }

export default function CloudPathPicker({ currentPath, onSelect, onClose }: CloudPathPickerProps) {
	const [path, setPath] = useState(() => currentPath.includes(":") ? currentPath : "");
	const [entries, setEntries] = useState<RcloneEntry[]>([]);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [retriedAtRemoteRoot, setRetriedAtRemoteRoot] = useState(false);
	const fetchDirectory = useCallback(async (targetPath: string) => { setLoading(true); setError(null); try { const response = await fetch(`${API_BASE}/rclone/ls?path=${encodeURIComponent(targetPath)}`, { headers: { "ngrok-skip-browser-warning": "true", Authorization: `Bearer ${localStorage.getItem("token")}` } }); if (!response.ok) { const message = await response.text(); if (response.status === 404 && targetPath.includes(":") && !retriedAtRemoteRoot) { setRetriedAtRemoteRoot(true); setPath(`${targetPath.split(":")[0]}:`); return; } setError(message || "Failed to list directory"); return; } const data = await response.json(); setEntries(data.entries || []); } catch { setError("Network error"); } finally { setLoading(false); } }, [retriedAtRemoteRoot]);
	useEffect(() => { fetchDirectory(path); }, [fetchDirectory, path]);
	const navigate = (name: string) => setPath(path.endsWith(":") || path.endsWith("/") ? `${path}${name}` : `${path}/${name}`);
	const goUp = () => { if (path.endsWith(":")) return; const parts = path.split("/"); if (parts.length === 1) setPath(path.split(":")[0] + ":"); else { parts.pop(); setPath(parts.join("/")); } };
	return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="cloud-picker-title"><div className="app-card flex max-h-[88dvh] w-full max-w-lg flex-col overflow-hidden"><header className="flex items-center justify-between border-b border-border-subtle px-4 py-4"><div><p className="eyebrow">Remote storage</p><h2 id="cloud-picker-title" className="mt-1 text-base font-semibold">Choose a folder</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-content-muted hover:bg-surface-strong hover:text-foreground" aria-label="Close folder picker"><X size={18} /></button></header><div className="flex gap-2 border-b border-border-subtle bg-surface-subtle/45 p-3"><button type="button" onClick={goUp} disabled={path.endsWith(":")} className="button-secondary min-h-10 px-3" aria-label="Go up one folder"><ChevronLeft size={17} /></button><input value={path} onChange={(event) => setPath(event.target.value)} className="app-input min-w-0 flex-1" aria-label="Current cloud path" /><button type="button" onClick={() => fetchDirectory(path)} className="button-secondary min-h-10 px-3" aria-label="Refresh folders"><RefreshCw size={16} /></button></div><div className="min-h-44 flex-1 overflow-y-auto p-3">{loading ? <div className="flex flex-col items-center justify-center gap-3 py-16 text-sm text-content-muted"><RefreshCw size={20} className="animate-spin text-accent" />Loading folders</div> : error ? <div className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-300">{error}</div> : entries.length === 0 ? <p className="py-16 text-center text-sm text-content-muted">This folder is empty.</p> : <div className="grid gap-1">{entries.filter((entry) => entry.IsDir).map((entry) => <button type="button" key={entry.Path} onClick={() => navigate(entry.Name)} className="flex min-h-12 items-center gap-3 rounded-xl px-3 text-left text-sm text-content-muted hover:bg-surface-subtle hover:text-foreground"><FolderOpen size={18} className="text-accent" />{entry.Name}</button>)}</div>}</div><footer className="flex flex-col-reverse gap-2 border-t border-border-subtle p-3 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="button-secondary">Cancel</button><button type="button" onClick={() => onSelect(path)} className="button-primary">Select this folder</button></footer></div></div>;
}
