import type { ReactNode } from "react";
import { Database, Image as ImageIcon, RefreshCw, Settings } from "lucide-react";

interface MaintenanceToolsSectionProps { maintenanceRunning: boolean; backfillRunning: boolean; thumbBackfillRunning: boolean; onMaintenance: () => void; onBackfill: () => void; onThumbBackfill: () => void; }

export default function MaintenanceToolsSection({ maintenanceRunning, backfillRunning, thumbBackfillRunning, onMaintenance, onBackfill, onThumbBackfill }: MaintenanceToolsSectionProps) {
	return <section className="space-y-4 border-t border-border-subtle pt-6"><div><p className="eyebrow">Admin utilities</p><h2 className="type-section-header mt-1 flex items-center gap-2"><Settings size={17} className="text-accent" />Maintenance tools</h2></div><div className="space-y-2"><ToolRow title="Sync database" description="Reconcile categories and local files." running={maintenanceRunning} runningLabel="Running" onClick={onMaintenance} icon={<RefreshCw size={17} />} /><ToolRow title="Backfill metadata" description="Fetch missing creators and captions." running={backfillRunning} runningLabel="Starting" onClick={onBackfill} icon={<Database size={17} />} /><ToolRow title="Generate thumbnails" description="Create previews for existing videos." running={thumbBackfillRunning} runningLabel="Starting" onClick={onThumbBackfill} icon={<ImageIcon size={17} />} /></div></section>;
}

function ToolRow({ title, description, running, runningLabel, onClick, icon }: { title: string; description: string; running: boolean; runningLabel: string; onClick: () => void; icon: ReactNode }) { return <div className="app-card-muted flex items-center gap-3 p-3 sm:p-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-accent/10 text-accent">{icon}</span><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-0.5 text-xs leading-5 text-content-muted">{description}</p></div><button type="button" onClick={onClick} disabled={running} className="button-secondary min-h-9 shrink-0 px-3 text-xs">{running ? runningLabel : "Run"}</button></div>; }
