import React, { useState } from "react";
import { Archive, ArrowLeftRight, Info, Trash2, X } from "lucide-react";
import SearchableSelect from "./SearchableSelect";

interface BatchOperationsProps { selectedCount: number; categories: string[]; onDelete: () => void; onZip: () => void; onMove: (targetCategory: string) => void; onSelectAll: () => void; onClearSelection: () => void; isLoading?: boolean; isZipping?: boolean; canManageFiles?: boolean; }

export default function BatchOperations({ selectedCount, categories, onDelete, onZip, onMove, onSelectAll, onClearSelection, isLoading = false, isZipping = false, canManageFiles = true }: BatchOperationsProps) {
	const [showMoveModal, setShowMoveModal] = useState(false);
	const [targetCategory, setTargetCategory] = useState("");
	const closeMove = () => { setShowMoveModal(false); setTargetCategory(""); };
	if (selectedCount === 0) return <div className="flex items-center justify-between gap-3 rounded-xl border border-dashed border-border-subtle bg-surface-subtle/35 px-3 py-2.5 sm:px-4"><span className="text-xs text-content-muted">Select files to manage them together</span><button type="button" onClick={onSelectAll} className="button-secondary min-h-9 px-3 text-xs">Select all</button></div>;

	return <>
		<div className="app-card flex flex-col gap-3 border-accent/25 bg-accent/5 p-3 sm:flex-row sm:items-center sm:justify-between sm:p-4">
			<div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-foreground">{selectedCount} selected</p><p className="hidden text-xs text-content-muted sm:block">Batch actions apply to every selected file</p></div><button type="button" onClick={onClearSelection} className="inline-flex items-center gap-1 text-xs font-semibold text-content-muted hover:text-foreground"><X size={14} />Clear</button></div>
			<div className="flex flex-wrap gap-2"><button type="button" onClick={onZip} disabled={isLoading || isZipping} className="button-secondary min-h-10 px-2 text-xs"><Archive size={14} />{isZipping ? "Zipping" : "Archive"}</button>{canManageFiles && <><button type="button" onClick={() => setShowMoveModal(true)} disabled={isLoading} className="button-secondary min-h-10 px-2 text-xs"><ArrowLeftRight size={14} />Move</button><button type="button" onClick={onDelete} disabled={isLoading} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-xl border border-red-400/25 bg-red-400/10 px-2 text-xs font-semibold text-red-300 transition hover:bg-red-400/20 disabled:opacity-45"><Trash2 size={14} />Delete</button></>}</div>
		</div>
		{showMoveModal && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 backdrop-blur-sm sm:items-center" role="dialog" aria-modal="true" aria-labelledby="move-files-title" onClick={closeMove}><div className="app-card w-full max-w-md p-5 sm:p-6" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Batch action</p><h2 id="move-files-title" className="mt-1 text-lg font-semibold">Move {selectedCount} files</h2></div><button type="button" onClick={closeMove} className="rounded-lg p-2 text-content-muted hover:bg-surface-strong hover:text-foreground" aria-label="Close move dialog"><X size={18} /></button></div><div className="mt-5"><label className="mb-2 block text-xs font-semibold text-content-muted">Destination category</label><SearchableSelect options={categories} value={targetCategory} onChange={setTargetCategory} placeholder="Choose a category" className="w-full" /></div><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={closeMove} className="button-secondary">Cancel</button><button type="button" onClick={() => { if (targetCategory.trim()) { onMove(targetCategory); closeMove(); } }} disabled={!targetCategory.trim() || isLoading} className="button-primary">Move files</button></div><p className="mt-4 flex items-center gap-1.5 text-xs text-content-subtle"><Info size={13} />Files keep their original names.</p></div></div>}
	</>;
}
