import React, { useState } from "react";
import { ChevronDown, ExternalLink, Play, RefreshCw, Trash2 } from "lucide-react";
import { DownloadJob, getDownloadUrl } from "../lib/api";
import StatusBadge from "./StatusBadge";
import { platformLabel } from "../lib/utils";
import CategoryBadge from "./CategoryBadge";

interface HistoryTableProps { jobs: DownloadJob[]; onRetry: (id: string) => void; onRedownload: (id: string) => void; onPreview: (job: DownloadJob) => void; onDelete: (id: string) => void; retryingIds?: Set<string>; maxRetries?: number; }

const formatDate = (timestamp: number | null | undefined) => timestamp ? new Date(timestamp).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "Not available";
const dateFolder = (timestamp: number | null | undefined) => timestamp ? new Date(timestamp).toISOString().slice(0, 10) : "unknown";

export default function HistoryTable({ jobs, onRetry, onRedownload, onPreview, onDelete, retryingIds = new Set(), maxRetries = 5 }: HistoryTableProps) {
	const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());
	const toggle = (id: string) => setExpandedRows((previous) => { const next = new Set(previous); if (next.has(id)) next.delete(id); else next.add(id); return next; });
	if (jobs.length === 0) return <div className="app-card-muted flex flex-col items-center justify-center py-16 text-center"><p className="text-sm font-semibold text-foreground">No history yet</p><p className="mt-1 text-xs text-content-muted">Completed and failed downloads will appear here.</p></div>;

	return <div className="space-y-3">
		<div className="hidden overflow-hidden rounded-2xl border border-border bg-surface lg:block"><table className="w-full text-left text-sm"><thead className="border-b border-border-subtle bg-surface-subtle/70 text-[10px] uppercase tracking-[0.15em] text-content-subtle"><tr><th className="px-4 py-3">Created</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border-subtle">{jobs.map((job) => <tr key={job.id} className="align-top hover:bg-surface-subtle/45"><td className="px-4 py-4 font-mono text-xs text-content-muted">{formatDate(job.createdAt)}</td><td className="max-w-[22rem] px-4 py-4"><p className="truncate text-sm font-medium" title={job.url}>{job.creator_name || job.filename || job.url}</p><p className="mt-1 truncate text-xs text-content-subtle">{job.platform && job.platform !== "unknown" ? platformLabel(job.platform) : "Source link"}</p></td><td className="px-4 py-4"><CategoryBadge category={job.category || "default"} /></td><td className="px-4 py-4"><StatusBadge status={job.status} /></td><td className="px-4 py-4"><HistoryActions job={job} onRetry={onRetry} onRedownload={onRedownload} onPreview={onPreview} onDelete={onDelete} retryingIds={retryingIds} maxRetries={maxRetries} /></td></tr>)}</tbody></table></div>
		<div className="flex flex-col gap-2 lg:hidden">{jobs.map((job) => { const expanded = expandedRows.has(job.id); return <article key={job.id} className="app-card overflow-hidden"><button type="button" onClick={() => toggle(job.id)} className="flex w-full items-start gap-3 p-4 text-left"><span className={`mt-0.5 rounded-lg bg-surface-subtle p-1.5 text-content-muted transition-transform ${expanded ? "rotate-180" : ""}`}><ChevronDown size={15} /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold">{job.creator_name || job.filename || job.url}</span><StatusBadge status={job.status} /></span><span className="mt-1 block truncate text-xs text-content-muted">{formatDate(job.createdAt)} <span className="px-1 text-content-subtle">/</span> {job.platform && job.platform !== "unknown" ? platformLabel(job.platform) : "Source link"}</span></span></button>{expanded && <div className="border-t border-border-subtle bg-surface-subtle/35 px-4 pb-4 pt-3"><dl className="grid gap-2 text-xs"><div><dt className="text-content-subtle">URL</dt><dd className="mt-0.5 break-all text-content-muted">{job.url}</dd></div>{job.filename && <div><dt className="text-content-subtle">Filename</dt><dd className="mt-0.5 break-all font-mono text-content-muted">{job.filename}</dd></div>}{job.error && <div><dt className="text-content-subtle">Error</dt><dd className="mt-0.5 text-red-300">{job.error}</dd></div>}</dl><div className="mt-4"><HistoryActions job={job} onRetry={onRetry} onRedownload={onRedownload} onPreview={onPreview} onDelete={onDelete} retryingIds={retryingIds} maxRetries={maxRetries} /></div></div>}</article>; })}</div>
	</div>;
}

function HistoryActions({ job, onRetry, onRedownload, onPreview, onDelete, retryingIds, maxRetries }: { job: DownloadJob; onRetry: (id: string) => void; onRedownload: (id: string) => void; onPreview: (job: DownloadJob) => void; onDelete: (id: string) => void; retryingIds: Set<string>; maxRetries: number }) {
	const retrying = retryingIds.has(job.id);
	const path = job.filename ? `data/${job.category || "default"}/${dateFolder(job.completedAt || job.createdAt)}/${job.filename}` : "";
	return <div className="flex flex-wrap items-center justify-end gap-1.5"><button type="button" onClick={() => window.open(job.url, "_blank", "noopener,noreferrer")} className="rounded-lg p-2 text-content-muted hover:bg-surface-strong hover:text-foreground" title="Open source" aria-label="Open source"><ExternalLink size={15} /></button>{job.status === "done" && job.filename && <button type="button" onClick={() => onPreview(job)} className="rounded-lg p-2 text-content-muted hover:bg-surface-strong hover:text-foreground" title="Preview" aria-label="Preview"><Play size={15} /></button>}{job.status === "done" && job.filename && <button type="button" onClick={() => window.open(getDownloadUrl(path), "_blank", "noopener,noreferrer")} className="rounded-lg p-2 text-emerald-300 hover:bg-emerald-400/10" title="Download" aria-label="Download"><ExternalLink size={15} /></button>}{job.status === "failed" && <button type="button" onClick={() => onRetry(job.id)} disabled={retrying || job.retries >= maxRetries} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg bg-accent/10 px-2.5 text-xs font-semibold text-accent disabled:opacity-45"><RefreshCw size={13} className={retrying ? "animate-spin" : ""} />{retrying ? "Retrying" : job.retries >= maxRetries ? "Limit reached" : "Retry"}</button>}{job.status === "missing" && <button type="button" onClick={() => onRedownload(job.id)} disabled={retrying} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg bg-amber-400/10 px-2.5 text-xs font-semibold text-amber-300 disabled:opacity-45"><RefreshCw size={13} className={retrying ? "animate-spin" : ""} />Retry</button>}<button type="button" onClick={() => onDelete(job.id)} className="rounded-lg p-2 text-content-muted hover:bg-red-400/10 hover:text-red-300" title="Delete history" aria-label="Delete history"><Trash2 size={15} /></button></div>;
}
